# Copied from https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver & https://github.com/KCL-BMEIS/lbr_fri_ros2_stack. Then merged to fit multi-robot setup
ur_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
iiwa7_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.01
